(set include BOOL off .)

(fth COMM-RING is
sort Ring .
op _+_ : Ring Ring -> Ring [assoc comm] .
op _*_ : Ring Ring -> Ring [assoc comm] .
ops 0 1 : -> Ring .
op - : Ring -> Ring .
vars x y z : Ring .
eq x + 0 = x .
eq x * 1 = x .
eq 1 * x = x .
eq x + -(x) = 0 .
eq -(0) = 0 .
eq -(-(x)) = x .
eq -(x + y) = -(x) + -(y) .
eq x + (y + -(x)) = y .
eq x * (y + z) = (x * y) + (x * z) .
eq x * -(y) = -(x * y) .
endfth)